name: example
description: A new Flutter project.

publish_to: "none"
version: 4.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_lock:
    path: ../
  local_auth: 1.1.0
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
